using System;
using System.Collections.Generic;
using System.Linq;
using CoPilot.ORM.Database;

namespace CoPilot.ORM.IntegrationTests.Models.BandSample
{
    public class FakeData
    {
        private readonly Random _rnd = new Random(new DateTime().Millisecond);

        public void Seed(DbWriter writer)
        {
            var genres = GetMusicGenres();
            var countries = GetCountriesWithCities();

            writer.Save<MusicGenre>(genres);
            writer.Save<Country>(countries, "Cities");
            var cities = countries.SelectMany(r => r.Cities).ToArray();

            var persons = GetPersons(cities, 5000);
            writer.Save<Person>(persons);

            var bands = GetBands(cities, 30);
            writer.Save<Band>(bands);

            var members = GetBandMembers(bands, persons);
            writer.Save<BandMember>(members);

            var recordings = GetRecordings(bands, genres);
            writer.Save<Recording>(recordings);

            var albums = GetAlbums(recordings);
            writer.Save<Album>(albums, "Tracks");
        }

        private Album[] GetAlbums(Recording[] recordings)
        {
            var bandRecordings =
                recordings.GroupBy(r => r.Band, (band, bandrecordings) => new {Key = band, Value = bandrecordings})
                    .ToDictionary(k => k.Key, v => v.Value);

            var albums = new List<Album>();

            foreach (var bandRecording in bandRecordings)
            {
                var orderedRecordings = bandRecording.Value.OrderBy(r => r.Recorded).ToList();

                while (orderedRecordings.Any())
                {
                    var tracks = _rnd.Next(Math.Min(orderedRecordings.Count, 6), Math.Min(orderedRecordings.Count, 14));
                    var albumrecordings = orderedRecordings.GetRange(0, tracks);
                    orderedRecordings.RemoveRange(0, tracks);
                    var t = 1;
                    var album = new Album
                    {
                        Title = albumrecordings.First().SongTitle,
                        Released = albumrecordings.Max(r => r.Recorded),
                        Tracks = albumrecordings.Select(r => new AlbumTrack
                        {
                            Recording = r,
                            TrackNumber = t++
                        }).ToList()
                    };
                    albums.Add(album);
                }
            }
            return albums.ToArray();
        }

        private Recording[] GetRecordings(Band[] bands, MusicGenre[] genres)
        {
            var recordings = new List<Recording>();
            
            foreach (var band in bands)
            {
                var genre = GetRandomItem(genres);
                var number = _rnd.Next(10, 500);
                var titles = new List<string>();
                for (var i = 0; i < number; i++)
                {
                    var recording = new Recording
                    {
                        Band = band,
                        Genre = genre,
                        Duration = TimeSpan.FromSeconds(_rnd.Next(60,60*7)),
                        Recorded = GetRandomDate(band.Formed),
                        SongTitle = GetAndRemoveRandomItem(titles, _songtitles)
                    };
                    recordings.Add(recording);
                }
            }

            return recordings.ToArray();
        }

        private Person[] GetPersons(City[] cities, int number)
        {
            var personNamesList = new List<string>();
            var persons = new List<Person>();
            for (var i = 0; i < number; i++)
            {
                var pers = new Person
                {
                    Name = GetAndRemoveRandomItem(personNamesList, _persons),
                    City = GetRandomItem(cities),
                    DateOfBirth = GetRandomDate(1920, 2000)
                };
                persons.Add(pers);
            }
            return persons.ToArray();
        }

        private Band[] GetBands(City[] cities, int number)
        {
            var bandNamesList = new List<string>();
            var bands = new List<Band>();
            for (var i = 0; i < number; i++)
            {
                var band = new Band
                {
                    Name = GetAndRemoveRandomItem(bandNamesList, _bandNames),
                    Based = GetRandomItem(cities),
                    Formed = GetRandomDate()
                };
                bands.Add(band);
            }
            return bands.ToArray();
        }

        private BandMember[] GetBandMembers(Band[] bands, Person[] people)
        {
            var peopleList = new List<Person>();
            var members = new List<BandMember>();
            var artistNames = new List<string>();
            var instrumentList = new List<string>();
            foreach (var band in bands)
            {
                
                var number = _rnd.Next(1, 7);
                for (var i = 0; i < number; i++)
                {
                    var left = _rnd.Next(10) > 7
                        ? (DateTime?) GetRandomDate(band.Formed, band.Formed.AddYears(1))
                        : null;

                    var joined = GetRandomDate(band.Formed, left ?? DateTime.Now);
                    var artistName = _rnd.Next(10) > 5 ? GetAndRemoveRandomItem(artistNames, _artistNames) : null;

                    var member = new BandMember
                    {
                        Band = band,
                        Person = GetAndRemoveRandomItem(peopleList, people),
                        Left = left,
                        ArtistName = artistName,
                        Joined = joined,
                        Instrument = GetAndRemoveRandomItem(instrumentList, new[] {"Lead guitar", "Rhythm guitar", "Bass guitar", "Drums", "Keyboard", "Vocals"})
                    };
                    members.Add(member);
                }
            }

            return members.ToArray();
        }

        private MusicGenre[] GetMusicGenres()
        {
            return new[]
            {
                new MusicGenre("Rock"),
                new MusicGenre("Metal"),
                new MusicGenre("Pop"),
                new MusicGenre("Folk"),
                new MusicGenre("Country"),
                new MusicGenre("Jazz"),
                new MusicGenre("R&B"),
                new MusicGenre("Hip Hop"),
                new MusicGenre("Classical")
            };
        }

        private Country[] GetCountriesWithCities()
        {
            return CountriesAndCityNames.Select(r => new Country
            {
                Name = r.Key,
                Cities = r.Value.Select(c => new City(c)).ToList()
            }).ToArray();
        }

        private DateTime GetRandomDate(int minYear = 1950, int? maxYear = null)
        {
            if (maxYear == null)
            {
                maxYear = DateTime.Now.Year;
            }
            return new DateTime(_rnd.Next(minYear, maxYear.Value), _rnd.Next(1,12), _rnd.Next(1, 28));
        }

        private DateTime GetRandomDate(DateTime minDate, DateTime? maxDate = null)
        {
            if (maxDate == null)
            {
                maxDate = DateTime.Now;
            }
            var maxDays = (int)(maxDate.Value - minDate).TotalDays;
            return minDate.AddDays(_rnd.Next(0,maxDays));
        }

        private T GetAndRemoveRandomItem<T>(List<T> picklist, IEnumerable<T> source)
        {
            if (!picklist.Any())
            {
                picklist.AddRange(source);
            }
            var index = _rnd.Next(0, picklist.Count - 1);

            var name = picklist[index];

            picklist.RemoveAt(index);

            return name;
        }

        private T GetRandomItem<T>(IReadOnlyList<T> source)
        {
            var index = _rnd.Next(0, source.Count - 1);

            return source[index];
        }

        private Dictionary<string, string[]> CountriesAndCityNames => new Dictionary<string, string[]>
        {
            { "Norway", new[] {"Stavanger", "Oslo", "Bergen", "Tronheim"}},
            { "Sweeden", new[] { "Stocholm", "Göteborg"}},
            { "England", new[] { "London", "Newcastle"}},
            { "USA", new[] {"Boston", "New York", "Seatle", "Miami"}}
        };

        private readonly string[] _artistNames = {
            "Glimmerdevourer Paw",
            "Vinemonkey Follower",
            "Alderrat Scale",
            "Jellyleopard Weasel",
            "Coppertoucan Dragon",
            "Rubycatcher Belly",
            "Peatgargoyle Iguana",
            "Canyonfollower Horse",
            "Quiltsnapper Paw",
            "Keenwanderer Dutchess",
            "Wooddart Doom",
            "Narrowfoot Scarer",
            "Marshgazelle Snake",
            "Redviper Lancer",
            "Neondolphin Wanderer",
            "Ringcap Rider",
            "Neonslave Flame",
            "Mistypig Vole",
            "Marblestag Chatter",
            "Pebbleboa Palm",
            "Juniperguardian Stalker",
            "Savagecrow Collar",
            "Grasscarp Shield",
            "Lightswoop Monkey",
            "Heavydrop Legs",
            "Paleprince Quester",
            "Pewterbear Dancer",
            "Smalldeer Sprite",
            "Equinoxhorn Coyote",
            "Foamgorilla Killer",
            "Berryfright Condor",
            "Bitterraven Lancer",
            "Rhinestonedeath Hisser",
            "Geoderazor Skull",
            "Alabastersargent Scarer",
            "Tabbydog Singer",
            "Sanddrop Scorpion",
            "Meadowstinger Warlock",
            "Sugarcoyote Neck",
            "Runelancer Touch",
            "Scratchgrasp Cloud",
            "Leadjackal Wolverine",
            "Dusttooth Robin",
            "Lightningboa Raptor",
            "Nightdog Dagger",
            "Ballisticbrow Shield",
            "Springlighter Mistress",
            "Tulipfairy Skinner",
            "Skitterscowl Saver",
            "Linenkangaroo Foe",
            "Daisybuffalo Trader",
            "Peppersamurai Rat",
            "Helixturner Arm",
            "Cloudgrin Mustang",
            "Quivercap Ogre",
            "Lightbow Giver",
            "Equinoxfly Gull",
            "Novawatcher Crown",
            "Nightmustang Swisher",
            "Fantasyviper Leader",
            "Cleargazelle Pixie",
            "Almondloon Cub",
            "Pricklestinger Drop",
            "Linengargoyle Hand",
            "Yellowstorm Terrier",
            "Patchseer Shift",
            "Nimbleray Duke",
            "Islandlancer Runner",
            "Weedmuse Jackal",
            "Powerbane Bane",
            "Stripepanther Hawk",
            "Coldhunter Dagger",
            "Juniperdancer Bee",
            "Foamface Puma",
            "Stellarcrest Griffin",
            "Roadlancer Glass",
            "Dourzebra Thorn",
            "Coppercougar Scribe",
            "Nebularobin Hiss",
            "Foamkicker Singer",
            "Gossamerbone Roach",
            "Sunrisescale Crafter",
            "Alpineshriek Charger",
            "Quilthawk Servant",
            "Rosegorilla Servant",
            "Dentroach Shaker",
            "Diamondmouse Stone",
            "Dewviper Saver",
            "Vividboot Throat",
            "Ashpaladin Beetle",
            "Stickyfoe Bard",
            "Checkerlion Face",
            "Pepperjester Eagle",
            "Purplesaver Wanderer",
            "Ballisticshark Voice",
            "Boldchiller Horse",
            "Pearknave Piper",
            "Crackwhale Ninja",
            "Relicwitch Carpet",
            "Mudant Thumb",
            "Squarehorn Knife",
            "Mirrorstalker Pirate",
            "Mountainhunter Carpet",
            "Giantknight Stinger",
            "Cakewarrior Mask",
            "Foamgorilla Nape",
            "Squareguardian Dancer",
            "Freedoom Unicorn",
            "Tulipfighter Grasp",
            "Arrowprince Sight",
            "Crystalgrasp Bow",
            "Rosehand Legs",
            "Pitchkoala Hound",
            "Geodeflame Shrieker",
            "Hollowspeaker Grin",
            "Chiselchanter Sage",
            "Venomcloud Gargoyle",
            "Sugarface Cloud",
            "Quartzpiper Sparrow",
            "Zenithshark Bard",
            "Sleetlord Bone",
            "Checkerfancier Bone",
            "Cliffhealer Mole",
            "Steelcougar Foe",
            "Linenroach Lantern",
            "Plumeface Curtain",
            "Brownbison Face",
            "Psychadelicarrow Collar",
            "Pollenrat Ape",
            "Eastjester Stone",
            "Fluffnape Reaper",
            "Hollowstag Walker",
            "Slowsoarer Palm",
            "Bushhyena Dart",
            "Darkripper Carver",
            "Heavythroat Otter",
            "Paintowl Runner",
            "Apricotdragon Speaker",
            "Shoreboa Ocelot",
            "Wildcarp Paladin",
            "Rosespirit Hero",
            "Patternhide Whale",
            "Diamondking Ray",
            "Crocustrader Grin",
            "Vinepixie Sloth",
            "Pyriteape Walker",
            "Dentsamurai Scourge",
            "Malachiteflasher Gorilla",
            "Smallguardian Hyena",
            "Curlyshark Spirit",
            "Shortrazor Slave",
            "Emberraven Raver",
            "Berylcarp Hide",
            "Mazewizard Raven",
            "Harvestox Lord",
            "Giantchanter Samurai",
            "Shadowforger Fin",
            "Fierceplayer Drop",
            "Zirconcentaur Fisher",
            "Buttercupdoom Goose",
            "Lunarvulture Bolt",
            "Shagcrystal Healer",
            "Fogyak Voice",
            "Vinelifter Heron",
            "Hurricanehowler Stealer",
            "Garnetpython Grabber",
            "Twistypirate Dagger",
            "Scythemole Mole",
            "Lapiskoala Bell",
            "Charmfly Hand",
            "Slowshriek Hawk",
            "Miremole Flame",
            "Lightningtwister Fish",
            "Tarcub Sting",
            "Midnightgoose Hawk",
            "Ragguardian Binder",
            "Scratchedge Owl",
            "Redshield Fly",
            "Calicokitten Crane",
            "Fuschiachin Nape",
            "Twilightlighter Bow",
            "Leadboar Sargent",
            "Destinyeye Neck",
            "Lightknife Tracker",
            "Greatfisher Ogre",
            "Treebat Centaur",
            "Snowedge Mustang",
            "Desertgambler Duck",
            "Sparkelk Spear",
            "Vividantler Witch",
            "Scytheswoop Grabber",
            "Dourhealer Foot",
            "Saberogre Ripper",
            "Springcatcher Devourer",
            "Crackmistress Drifter",
            "Kiwilighter Trader",
            "Bitterdutchess Mare",
            "Juniperhisser Rat",
            "Walnutgrasp Terrier",
            "Runetail Stalker",
            "Sundoom Mole",
            "Streamfriend Toucan",
            "Cactuspython Paw",
            "Longthief Mole",
            "Sequoiaboar Head",
            "Cosmicjay Weasel",
            "Roundwolverine Gull",
            "Scratchneck Sting",
            "Dotrazor Hyena",
            "Cedardive Spur",
            "Fancycurtain Rider",
            "Glacierboot Friend",
            "Pebblecloud Parrot",
            "Shyshrieker Tiger",
            "Sugarduck Wolverine",
            "Sourbraid Pirate",
            "Shallowtrack Goat",
            "Wellmonkey Fright",
            "Mireskinner Rib",
            "Coldcloud Spur",
            "Bowlord Elk",
            "Hotthumb Death",
            "Clovertrader Bolt",
            "Translucentsamurai Elf",
            "Chainfollower Falcon",
            "Trailhero Lighter",
            "Stitchbow Puma",
            "Sagebee Lightning",
            "Silentrat Saver",
            "Firecoyote Puma",
            "Trailstone Gazelle",
            "Notchotter Hair",
            "Cursewizard Paladin",
            "Kiwiknave Oriole",
            "Irisdagger Lion",
            "Curserat Roar",
            "Tundrasnap Thief",
            "Timescribe Kangaroo",
            "Fantasycockatoo Gecko",
            "Browneye Ox",
            "Daffodillighter Thief",
            "Cleareye Weed",
            "Vividjackal Thorn",
            "Irisgem Weed",
            "Hurricanetrader Tongue",
            "Brickbat Painter",
            "Hotthorn Frill",
            "Foresttwister Biter",
            "Glitterbiter Hide",
            "Kiwifrill Raccoon",
            "Tinyhowler Foe",
            "Redcrusher Terrier",
            "Peathisser Knife",
            "Razortwister Viper",
            "Threadleader Wanderer",
            "Metallady Myth",
            "Laserhound Stallion",
            "Birdhealer Hawk",
            "Tabbyfairy Boa",
            "Sabersamurai Trader",
            "Chromesnapper Wasp",
            "Plumpprincess Razor",
            "Razorbraid Brow",
            "Justpython Dancer",
            "Rivermyth Gem",
            "Platinumbow Back",
            "Chattercrystal Wizard",
            "Redeagle Cub",
            "Walnutrazor Grin",
            "Brickthief Dancer",
            "Basaltshift Terrier",
            "Flowerhand Roach",
            "Beadminnow Hugger",
            "Ivysnake Stag",
            "Dandymuse Wanderer",
            "Noblefisher Dancer",
            "Chatterwatcher Princess",
            "Obsidiankeeper Samurai",
            "Linenshaker Giver",
            "Bravelancer Crane",
            "Shallowbutterfly Howler",
            "Treasurecrane Leg",
            "Plumepig Swoop",
            "Slowhawk Crusher",
            "Coconutraccoon Piper",
            "Bogmask Scowl",
            "Micaheron Weaver",
            "Roseheron Snake",
            "Berylwhale Hare",
            "Sheerjaw Rabbit",
            "Slimeseeker Rabbit",
            "Bogkiller Hound",
            "Lacesaver Hawk",
            "Discocrafter Flame",
            "Embersight Wolf",
            "Indigoshirt Grin",
            "Sheerdragon Leopard",
            "Shadehowler Hyena",
            "Jasperdrifter Swoop",
            "Snapdragondevourer Eater",
            "Meadowlegend Keeper",
            "Chipnape Drifter",
            "Thundereater Ogre",
            "Boomserpent Seed",
            "Pondscowl Cougar",
            "Platinummoose Rib",
            "Neonfinger Butterfly",
            "Treasurespike Brow",
            "Cometogre Warrior",
            "Mazesprite Fly",
            "Speckleminnow Devourer",
            "Picklesnout Lord",
            "Battleviper Salmon",
            "Charmshield Chopper",
            "Iridescentshift Eater",
            "Runedart Robin",
            "Titaniumpanther Leader",
            "Grayqueen Reaper",
            "Pickleshriek Grabber",
            "Sapphiremuse Venom",
            "Chainkicker Swoop",
            "Nettlehornet Weasel",
            "Mangopainter Swallow",
            "Ripplethroat Saver",
            "Redbuffalo Razor",
            "Rhinestoneslicer Gargoyle",
            "Laserfisher Legend",
            "Prismwing Chin",
            "Sugarseeker Singer",
            "Vividspike Belly",
            "Skysnapper Unicorn",
            "Riftmuse Antler",
            "Narrowmyth Ringer",
            "Zirconkangaroo Palm",
            "Stitchdiver Hyena",
            "Petalmaster Parrot",
            "Slimemaster Scowl",
            "Zirconshoulder Shield",
            "Agateknave Weed",
            "Cottonmuse Hero",
            "Coconuthide Hunter",
            "Savagespeaker Foe",
            "Charmhare Serpent",
            "Twilightsamurai Singer",
            "Legendslave Hugger",
            "Shellchest Head",
            "Blazejaw Gambler",
            "Crystalbrow Monkey",
            "Gingerthroat Dog",
            "Mazestinger Arm",
            "Rustlegend Raccoon",
            "Flanneldagger Doom",
            "Patternglass Fin",
            "Flameprincess Bone",
            "Emberbelly Lasher",
            "Springburn Viper",
            "Rampanthornet Fighter",
            "Glimmerslave Mustang",
            "Sandeater Scowl",
            "Stormgazelle Howler",
            "Zircondeath Eagle",
            "Hurricanebell Crane",
            "Rattlebell Shirt",
            "Treasurehide Track",
            "Slashshriek Oriole",
            "Prongparrot Moose",
            "Battlehound Raccoon",
            "Justjay Heron",
            "Lightningscorpion Scorpion",
            "Narrowparrot Vole",
            "Fatejaw Bison",
            "Weedseeker Flier",
            "Obsidianface Follower",
            "Twilightgrin Drifter",
            "Ivorysprite Nose",
            "Baldrover Wolverine",
            "Crackkeeper Cloak",
            "Azurelancer Cougar",
            "Ragvoice Snake",
            "Lieridge Trader",
            "Nimblelady Rider",
            "Flinttongue Snarl",
            "Hornsnapper Fly",
            "Ribbonlighter Nape",
            "Desertterrier Slicer",
            "Caramelgorilla Flame",
            "Bluethief Boot",
            "Stormrider Python",
            "Coldhawk Legend",
            "Sparknose Dog",
            "Basaltdive Oriole",
            "Hickoryrat Mark",
            "Chocolatefoe Salmon",
            "Treewhale Paw",
            "Sagefairy Gambler",
            "Bravesaver Hyena",
            "Bandhawk Rat",
            "Saltsight Chest",
            "Gloryhiss Singer",
            "Sandslave Swallow",
            "Marblerider Queen",
            "Glittersnarl Shrieker",
            "Regalfin Thorn",
            "Madpalm Eagle",
            "Deepfly Eagle",
            "Wintercoyote Skull",
            "Baldwatcher Master",
            "Swamplasher Wyrm",
            "Graycat Bard",
            "Rampantbird Lynx",
            "Applehead Stealer",
            "Lilyeater Touch",
            "Berrykoala Hair",
            "Treasurejay Lynx",
            "Silverpirate Fox",
            "Brasshowler Mask",
            "Feathercentaur Whip",
            "Purpleshift Watcher",
            "Dustrunner Ox",
            "Spicemyth Lightning",
            "Lightgrabber Voice",
            "Butterfairy Stork",
            "Hollowboa Eye",
            "Daisymouse Goose",
            "Nettlebuffalo Head",
            "Quasarleopard Donkey",
            "Puddledonkey Fighter",
            "Desertkitten Thumb",
            "Flamehorn Crest",
            "Atomcoyote Cub",
            "Glenfin Wing",
            "Woolstork Deer",
            "Prismback Lady",
            "Applefoot Scribe",
            "Fossillancer Scorpion",
            "Foamhyena Speaker",
            "Snapdragonsargent Pegasus",
            "Brindlediver Gorilla",
            "Rogueracer Chanter",
            "Discochatter Swoop",
            "Fiercecatcher Snake",
            "Cordbell Bird",
            "Battlespirit Snapper",
            "Pearape Turner",
            "Flickerspike Skinner",
            "Honeysucklemark Weaver",
            "Planethealer Stalker",
            "Steelripper Spear",
            "Ribbonsage Crow",
            "Bushstag Gorilla",
            "Brassmaster Crusher",
            "Beadfighter Player",
            "Tulipsnake Paw",
            "Jellywalker Rover",
            "Marblemaster Mouse",
            "Glacierhound Goat",
            "Coralpalm Song",
            "Leadstealer Knife",
            "Bristlebunny Voice",
            "Wellroarer Crystal",
            "Bluejaguar Elf",
            "Wheatvenom Glazer",
            "Ribbonstone Ant",
            "Jellyjester Dolphin",
            "Veilcoyote Quester",
            "Boldscourge Stag",
            "Peppermustang Raptor",
            "Shagcloak Mark",
            "Leadwhale Bug",
            "Marblemaster Shield",
            "Frecklesnake Lynx",
            "Glowrazor Killer",
            "Spicewizard Elk",
            "Rainbowflier Cub",
            "Zirconhead Goose",
            "Powergriffin Eagle",
            "Puzzlefly Lion",
            "Northmask Hugger",
            "Foilwyrm Vulture",
            "Riverleopard Cloud",
            "Sheercondor Chanter",
            "Patchgazelle Raven",
            "Mangogorilla Fancier",
            "Aquamarinearrow Fly",
            "Flamegriffin Tiger",
            "Irisbison Myth",
            "Luckmind Stag",
            "Saberdrop Collar",
            "Swamphisser Gull",
            "Dandycentaur Venom",
            "Mesquitehand Reaper",
            "Skittersnap Wolf",
            "Leathercrystal Dutchess",
            "Fishgazelle Hunter",
            "Alpineboot Gambler",
            "Alpinequester Wasp",
            "Pitchshirt Snap",
            "Baldroach Storm",
            "Juniperwhimsey Bunny",
            "Riverzebra Hoof"
        };
        private readonly string[] _persons = {
            "Vern Heaney",
            "Miss Eino Pfeffer",
            "Taylor Dickinson",
            "Kali Paucek",
            "Rickey Rau IV",
            "Rebeca Thompson",
            "Axel King",
            "Chelsea Ward",
            "Ms. Matteo Connelly",
            "Patience Gutmann",
            "Jacinthe Quitzon",
            "Katelyn Romaguera",
            "Pete Heidenreich",
            "Jacinthe Wilkinson",
            "Micaela Bauch",
            "Ernest Purdy",
            "Abby Williamson",
            "Dr. Donny Ondricka",
            "Emilie Abernathy",
            "Grace Marvin",
            "Edward Botsford",
            "Otha Ferry",
            "Lon Crist",
            "Ellsworth Kling",
            "Abbigail Cummerata",
            "Miss Scarlett Sanford",
            "Milton Wolf",
            "Marlin Schmidt",
            "Macy Wolf II",
            "Kaylah Turner",
            "Josephine Beahan",
            "Shaina Muller",
            "Mrs. Hilbert Streich",
            "Helene Mraz",
            "Haskell Towne",
            "Colby King DVM",
            "Dejon Smitham",
            "Daija Goodwin DDS",
            "Dr. Orlando Sauer",
            "Odie Sawayn",
            "Jasper Moen",
            "Kenton Fritsch",
            "Courtney Zieme",
            "Andres Tremblay",
            "Genoveva Nicolas",
            "Leopoldo Braun",
            "Damaris Tillman",
            "Bridget Raynor",
            "Trever Gutkowski",
            "Neha Berge",
            "Morris Jones",
            "Mr. Jalon Huels",
            "Diego Nikolaus II",
            "Sarah Mayert",
            "Era Nicolas",
            "Brooklyn Pacocha",
            "Roma Brakus",
            "Oda Terry",
            "Delmer Wiegand MD",
            "Alta Bernhard",
            "Rey Gulgowski",
            "Albina Langworth",
            "Caesar Skiles",
            "Malcolm Jacobi",
            "Electa Bergnaum",
            "Roscoe Gorczany V",
            "Orlando Casper",
            "Alf Bartoletti",
            "Frederik D'Amore III",
            "Thora Dare DVM",
            "Brigitte McLaughlin",
            "Noe Beier",
            "Isaiah O'Kon",
            "Dr. Willow Purdy",
            "Ransom Nader DVM",
            "Bo Beahan",
            "Leila Kub",
            "Abbie Thompson",
            "Tremayne Runte",
            "Jayce Eichmann",
            "Drew Krajcik",
            "Nils Green",
            "Reagan Cole Sr.",
            "Santina McLaughlin",
            "Elliot Reichel",
            "Mr. Jordy Zboncak",
            "Chaya Schoen MD",
            "Jaden O'Reilly",
            "Naomi Padberg DVM",
            "Jackie Cremin",
            "Nathan Hermiston",
            "Lilyan Anderson",
            "Ms. Izabella Morissette",
            "Coty Flatley V",
            "Timmy Marks",
            "Anne Murray",
            "Jacquelyn Treutel I",
            "Elvie Bauch",
            "Roy Larkin III",
            "Kaitlyn Greenfelder",
            "Effie Dietrich",
            "Miss Ashley McClure",
            "Dr. Elroy Medhurst",
            "Mallie Blanda",
            "Retha Hackett",
            "Trent Upton V",
            "Mr. Irma Kuhlman",
            "Ashtyn Weber",
            "Mrs. Dejah Sporer",
            "Madyson Goyette",
            "Jacquelyn Ondricka",
            "Magnus Koepp",
            "Candace Sauer",
            "Miss Cassandre O'Keefe",
            "Roxane Beatty",
            "Ervin Waters",
            "Joyce Keebler",
            "Miss Trenton Kunde",
            "Emiliano Auer",
            "Easton Trantow",
            "Vernie McClure",
            "Zack Denesik",
            "Justice Becker",
            "Cleve Stokes",
            "Lloyd Fadel",
            "Jaylen Ward",
            "Danyka Krajcik",
            "Caesar Cole",
            "Tate Schmeler",
            "Bridgette Leffler",
            "Johnnie Altenwerth",
            "Graciela Watsica",
            "Florencio Renner",
            "Naomie Borer V",
            "Mrs. Jordy Boyle",
            "Gerson Homenick",
            "Casper Schmitt",
            "Brandon Connelly",
            "April Schneider",
            "Litzy Bergnaum",
            "Ellsworth Hammes MD",
            "Brandyn Rogahn",
            "Jovani McCullough PhD",
            "Ike Pouros",
            "Allan Purdy",
            "Carleton Wisozk",
            "Mrs. Myriam Kiehn",
            "Melyna Streich I",
            "Lempi Leffler",
            "Tre Hahn V",
            "Devin Greenholt",
            "Ara Romaguera",
            "Solon Aufderhar",
            "Lesley Lubowitz",
            "Ms. Giovanny Runolfsdottir",
            "Ernest Gusikowski",
            "Nikita Windler",
            "Carmel Turcotte",
            "Myrtice Kautzer",
            "Luther Hayes",
            "Cicero Kovacek MD",
            "Audie Keebler",
            "Jeffry Kulas",
            "Autumn Kuhic",
            "Mac Bashirian",
            "Collin Anderson",
            "Mr. Verla Rath",
            "Lazaro Pfeffer",
            "Lelia Lang",
            "Alanna Senger PhD",
            "Vaughn Murazik",
            "Eudora Rutherford III",
            "Adan Prohaska",
            "Hector Waters",
            "Savanna Funk",
            "Prudence Bradtke",
            "Nathanael Mayer",
            "Felicita Weimann",
            "Mrs. Arne Towne",
            "Stewart Satterfield MD",
            "Dr. Micheal Kemmer",
            "Agustin Reinger",
            "Mr. Benjamin Kub",
            "Johnnie Walter",
            "Payton Rosenbaum",
            "Zella Armstrong",
            "Mariela Swift",
            "Kaia Hills",
            "Meredith Senger",
            "Meda Cruickshank",
            "Jeramy Jenkins",
            "Jason Ondricka",
            "Dr. Annabel Hilpert",
            "Rico Murazik",
            "Jeffery Corkery Jr.",
            "Isaias Stamm",
            "Eulalia Nicolas",
            "Vesta Mueller",
            "Gaston Ortiz",
            "Reginald Bogisich",
            "Israel Frami",
            "Felicita Feeney",
            "Dr. Kyleigh Schaden",
            "Bennie Wiza",
            "Maxwell Rath",
            "Alice Fahey",
            "Myrtis Rowe",
            "Keith Legros Sr.",
            "Lazaro Murphy IV",
            "Vincenzo Metz",
            "Micaela Kohler",
            "Miss Arthur Herman",
            "Summer Abernathy",
            "Chelsey Maggio III",
            "Albin Koelpin IV",
            "Rachelle Wilkinson",
            "Winona Carroll",
            "Elza Carter",
            "Dr. Waino Brakus",
            "Carmella Runte",
            "Jamarcus Romaguera",
            "Miss Jeffrey Mohr",
            "Devin Auer",
            "Vance Graham",
            "Eldon Langworth",
            "Christa Rowe",
            "Gino Ebert II",
            "Dewayne Schmeler DDS",
            "Reina Dickens",
            "Johanna Harber III",
            "Larry Ondricka",
            "Patsy Lind",
            "Ivory Berge",
            "Alexa Marvin",
            "Pearline Bins",
            "Mrs. Anjali Adams",
            "Madisyn Friesen III",
            "Vicky Bergnaum",
            "Gaetano Bosco",
            "Bernard Schumm",
            "Wendell Leannon",
            "Noel Hills",
            "Joaquin Eichmann",
            "Thomas Lakin",
            "Shaina Hills",
            "Guadalupe Blick",
            "Katrine Hudson",
            "Cloyd Powlowski III",
            "Shanny Carter V",
            "Ms. Melissa Keebler",
            "Holly Schaden I",
            "Roy Skiles",
            "Kurtis Reilly",
            "Ms. Dovie Hirthe",
            "Tressa Treutel",
            "Rex Padberg",
            "Esther McClure",
            "Weldon Keebler",
            "Cory Murazik",
            "Moises Gleason",
            "Junius Ondricka",
            "Ms. Kenyatta Stehr",
            "Ms. Anna Greenfelder",
            "Frances Schiller DDS",
            "Ignatius Price I",
            "Lempi Mosciski DVM",
            "Ed O'Kon",
            "Wilfredo Conn",
            "Mattie Runte",
            "Rickey DuBuque",
            "Nina Harvey",
            "Trent Smitham",
            "Zoey Wolf",
            "Maude Eichmann",
            "Heather Steuber",
            "Kobe Harber",
            "Mr. Gene Braun",
            "Madge Haley",
            "Ernestine MacGyver",
            "Kaitlin Windler",
            "Joy Tillman IV",
            "Miss Madilyn Sporer",
            "Isaiah Kemmer",
            "Kaylee Tremblay",
            "Verona Von IV",
            "Dr. Oliver Wilkinson",
            "Dr. Berneice Cole",
            "Jeffrey Russel",
            "Breana Hickle",
            "Salvatore McGlynn",
            "Mrs. Trystan Ondricka",
            "Eliane Wiegand II",
            "Mrs. Isidro Dare",
            "Virginia Stroman",
            "Maegan Schmidt Sr.",
            "Etha Connelly II",
            "Mose Glover",
            "Cyril Stoltenberg",
            "Emelia Wilderman",
            "Matteo Terry",
            "Katlyn Padberg",
            "Randi Marvin",
            "Anderson Batz",
            "Edd Nolan",
            "Rhea Pacocha I",
            "Eunice McDermott",
            "Jarret Heller",
            "Valentina Turcotte",
            "Catalina Ferry",
            "Zoey Moore",
            "Ivah Donnelly V",
            "Juliet Hegmann",
            "Maddison Ernser V",
            "Ceasar Armstrong",
            "Kayla Blanda",
            "Foster Kiehn",
            "Broderick Kuhic",
            "Verona Wyman",
            "Everette Bauch",
            "Giovanni Harris",
            "Mable Luettgen",
            "Elijah Krajcik Sr.",
            "Annette Kohler",
            "Adaline Dach",
            "Ivy McClure",
            "Mr. Olga Mayert",
            "Mayra VonRueden DDS",
            "Kane Strosin",
            "Letha Jakubowski",
            "Ms. Ralph Pfeffer",
            "Jamil Koss",
            "Mr. Trace Kuhn",
            "Jordan Abbott",
            "Elva Emard",
            "Mireille Gulgowski",
            "Elijah Von",
            "Kasandra Haley",
            "Archibald Borer",
            "Hester Kertzmann II",
            "Anastasia Turner",
            "Emie Jacobi",
            "Zachery Blanda",
            "Hilma VonRueden",
            "Kacey Rowe",
            "Sylvan Berge",
            "Miss Joesph Ebert",
            "Eden Simonis",
            "Joe Nolan",
            "Arjun Schroeder",
            "Gertrude Mayer",
            "Ms. Maverick Littel",
            "Norma Hyatt",
            "Miss Javonte Zemlak",
            "Malika Trantow",
            "Rozella Hickle",
            "Sunny Gleason II",
            "Laurel Cronin",
            "Miss Isabell Russel",
            "Alessandro Stracke",
            "Unique Kub",
            "Katelyn Ullrich",
            "Rita Dooley",
            "Miss Braden Kreiger",
            "Annamarie Blanda",
            "Asia Hamill II",
            "Travon Daniel",
            "Isobel Schuppe",
            "Clifton Hartmann",
            "Candido O'Conner",
            "Angel Stracke",
            "Johnathan Konopelski",
            "Peyton Ruecker",
            "Laney Rippin",
            "Fannie Greenholt",
            "Dr. Viva Schultz",
            "Dr. Javier Gaylord",
            "Kelvin Harber",
            "Dr. Quinn Greenfelder",
            "Rosalind Konopelski",
            "Gregoria Witting",
            "Jamir Welch",
            "Mrs. Zoey Ondricka",
            "Colton O'Conner Jr.",
            "Mr. Moshe Kuphal",
            "Alysa Sipes",
            "Burnice Tremblay",
            "Deontae Krajcik",
            "Brady Weissnat",
            "Marcelina Larson",
            "Miss Briana Daniel",
            "Dr. Sydney Hackett",
            "Stephan Abbott",
            "Caden McClure",
            "Lauretta Little III",
            "Elias Jerde",
            "Soledad Medhurst",
            "Syble Bechtelar",
            "Lavinia Cummings",
            "Efrain Pfannerstill",
            "Shana Weissnat",
            "Titus Sipes",
            "Guy Bauch",
            "Kendra Armstrong",
            "Lamont Kuphal",
            "Mr. Nicola Hettinger",
            "Heath Grant",
            "Ronny Koss",
            "Kirstin Daugherty",
            "Mr. Sofia Bernier",
            "Kira Hintz",
            "Jaida Satterfield",
            "Hal Kling",
            "Mervin Reinger",
            "Simone Schroeder",
            "Rahul Bashirian DDS",
            "Elliot Hodkiewicz",
            "Mrs. Michael Parisian",
            "Elta Marvin V",
            "Miss Clyde Waters",
            "Amani Flatley Sr.",
            "Cade Dach",
            "Emily Kertzmann",
            "Adelia Klein",
            "Kristin Daniel",
            "Joshuah Padberg Jr.",
            "Aiden Shields",
            "Jaqueline McKenzie",
            "Tyrese Quigley",
            "Coralie Williamson",
            "Ashley Ryan",
            "Jovani Gislason",
            "Hilton Kulas",
            "Rebeka Christiansen",
            "Ethyl Kerluke",
            "Darwin Stehr",
            "Rae Farrell",
            "Madelyn Ziemann",
            "Wilhelmine Eichmann",
            "Delphine Becker",
            "Khalil Rempel",
            "Hailie Osinski",
            "Cecilia Sipes",
            "Verla Rohan",
            "Tiara Huel",
            "Dr. Liza Krajcik",
            "Cora Luettgen",
            "Samanta Blanda Sr.",
            "Lola Raynor",
            "Greta Runte IV",
            "Troy Larkin",
            "Taylor Spencer",
            "Janessa Koch",
            "Giuseppe Lemke",
            "Moises Goyette",
            "Amira Kris",
            "Ms. Lindsay MacGyver",
            "Chaim Morar IV",
            "Cynthia Kuphal",
            "Leslie Glover",
            "Alice Jacobs",
            "Rylan Rau",
            "Ryley Baumbach",
            "Theresia Bednar",
            "Anastacio Okuneva",
            "Edgar Larkin",
            "Sarina Fritsch",
            "Torey Stanton",
            "Johnnie Krajcik",
            "Rex Schmidt",
            "Dianna Hermiston III",
            "Dane Parker",
            "Lessie Bechtelar",
            "Adan Tremblay",
            "Mr. Barrett Macejkovic",
            "Emiliano Hettinger II",
            "Andy Anderson",
            "Gabriel Fritsch",
            "Brenden Farrell",
            "Lupe Wisoky III",
            "Darien Jones",
            "Delfina Kris",
            "Maverick Borer PhD",
            "Barry Sipes",
            "Brett Bednar",
            "Erin Schowalter Sr.",
            "Mr. Vesta Emmerich",
            "Marion Tillman",
            "Brittany Ferry",
            "Beaulah Welch",
            "Mrs. Gustave Reilly",
            "Gene Littel",
            "Avery Langosh",
            "Yazmin Mante",
            "Maya Kilback I",
            "Jorge Koch",
            "Aurelie Hilll Sr.",
            "Tyrel Wunsch",
            "Julio Bergnaum",
            "Morris Crooks",
            "Eryn Lakin"
        };

        private readonly string[] _bandNames = {
            "Boursin Tank",
            "Electric Tilsit",
            "Soul of the Bergader",
            "Cuajada Witch",
            "Malmsteen's Olivet Cendre",
            "Gloucester Thunder",
            "Geitost Messiah",
            "Rancid Castellano",
            "Tete de Moine Transgressor",
            "Paneer Prophets",
            "American Cheese Revenge",
            "Fresh Mozzarella Storm",
            "Crushed Aragon",
            "Angel of the Casciotta di Urbino",
            "Corrosive Galette Lyonnaise",
            "Longhorn Gods",
            "Lecherous Curworthy",
            "Cuajada Beast",
            "Saint Fourme de Haute Loire",
            "Profane Acorn",
            "Longhorn Temple",
            "Wild Saint-Paulin",
            "Coven Saaland Pfarr",
            "Ministry of the Little Rydings",
            "L'Ecir de l'Aubrac Veins",
            "Profane Etorki",
            "San Simon Vengeance",
            "God of the Patefine Fort",
            "Atom Oszczypek",
            "Gorgonzola Hell",
            "Motorized Crayeux de Roncq",
            "Monastery Cheeses Master",
            "Rancid Marble Cheddar",
            "Mondseer Flesh",
            "God of the Sap Sago",
            "Monsters of the Siraz",
            "Queso de Murcia Demons",
            "Soul of the Evora De L'Alentejo",
            "Chevres Dreams",
            "Caravane Reaper",
            "Burning Montasio",
            "Seething Fin-de-Siecle",
            "Marble Cheddar Entrails",
            "Barbaric Dry Jack",
            "Steel Boeren Leidenkaas",
            "Canestrato Mutilation",
            "Esrom Horde",
            "Evil Evora De L'Alentejo",
            "Alien Parmesan (Parmigiano)",
            "Diseased Caerphilly",
            "Sick Camembert de Normandie",
            "Port Nicholson Widow",
            "Galette Lyonnaise Sin",
            "Dead Explorateur",
            "Destiny's Queso Jalapeno",
            "Lucifer's Mascarpone (Australian)",
            "Bad Rollot",
            "Bosworth Reich",
            "Disturbed Xynotyro",
            "God of the Fourme de Montbrison",
            "Lecherous Creme Fraiche",
            "Sweet Buxton Blue",
            "Death Ricotta (Australian)",
            "Crushed Vulscombe",
            "Avaxtskyr Coven",
            "Queso del Tietar Hearse",
            "Kikorangi Widow",
            "Brain Cotija",
            "Stabbing Crowley",
            "Quartirolo Lombardo Death",
            "Sweet Crottin de Chavignol",
            "Brain Chabichou",
            "Reggianito Wolf",
            "Curworthy Snake",
            "Angel of the Longhorn",
            "Blood Mihalic Peynir",
            "Screaming Cheshire",
            "Goodbye Fondant de Brebis",
            "Croghan Hoof",
            "Desecrated Tomme des Chouans",
            "Ossau-Iraty Widow",
            "Goodbye Croghan",
            "Grabetto Cthulhu",
            "Viking Emlett",
            "Chabichou Smack",
            "Friesekaas Wrath",
            "Swaledale Altar",
            "Croghan Carnage",
            "Occult Scamorza",
            "Killer Waimata Farmhouse Blue",
            "Livarot Krieg",
            "Tomme d'Abondance Thunder",
            "Pelardon des Corbieres Sword",
            "Boulette d'Avesnes Cruelty",
            "Beasts of the Dunlop",
            "Cachaille Sorrow",
            "Maniacal Fromage a Raclette",
            "Rancid Brebis du Lavort",
            "Deviant Stilton",
            "Tronchon Tear"
        };

        private readonly string[] _songtitles = {
            "In the cold",
            "Running like it",
            "The base is so strong",
            "Feel the mountain king",
            "Playing the walls",
            "Rock you",
            "Singing to get you",
            "The guitars",
            "I like hell",
            "Playing the cold",
            "Battle of the halls of",
            "In the halls of the",
            "Can't get you all night",
            "Feel the beast is so",
            "Flying the guitars",
            "Speed metal is so strong",
            "Playing the guitars",
            "Tear down the halls of",
            "Battle of the cold",
            "Tear down the base is",
            "Flying the base is so",
            "In the beast is so",
            "I hate you all night",
            "The halls of the cold",
            "Flying the beast is so",
            "Flying the cold",
            "Love is near",
            "Tear down the guitar",
            "In the dragon",
            "The heat is so strong",
            "The cold",
            "In the guitars",
            "The mountain king",
            "I miss you all night",
            "Flying the halls of the",
            "Battle of the beast is",
            "Speed metal is near",
            "The walls",
            "Tear down the mountain king",
            "Playing the halls of the",
            "Coming to get you all",
            "Tear down the cold",
            "The beast is on",
            "Battle of the walls",
            "In the base is on",
            "Tear down the beast is",
            "Feel the heat is king",
            "Feel the base is near",
            "In the heat is king",
            "The halls of the base",
            "Playing the heat is near",
            "The halls of the halls",
            "Battle of the base is",
            "Flying the heat is so",
            "Coming to you",
            "Feel the guitars",
            "Can't get you",
            "The dragon",
            "The base is king",
            "Feel the halls of the",
            "Love is so fat",
            "Speed metal is so fat",
            "Flying the mountain king",
            "Tear down the guitars",
            "Playing the base is so",
            "Flying the walls",
            "The base is on",
            "The beast is king",
            "Singing to get enough",
            "Feel the walls",
            "Love is king",
            "The halls of the mountain",
            "Singing to get you all",
            "The halls of the guitar",
            "Love is on",
            "Tear down the heat is",
            "Battle of the mountain king",
            "Coming to get enough",
            "Battle of the guitar",
            "In the heat is on",
            "In the mountain king",
            "The guitar",
            "In the base is king",
            "The heat is king",
            "Speed metal is on",
            "Feel the heat is so",
            "The halls of the dragon",
            "Playing the beast is so",
            "Playing the heat is so",
            "Coming to you all night",
            "The beast is so strong",
            "Feel the base is on",
            "The beast is so fat",
            "Flying the beast is near",
            "In the walls",
            "Feel the dragon",
            "The heat is so fat",
            "In the guitar",
            "Battle of the heat is",
            "Feel the guitar",
            "Battle of the dragon",
            "Feel the base is so",
            "In the heat is so",
            "Feel the beast is king",
            "Tear down the dragon",
            "Flying the guitar",
            "Playing the heat is king",
            "Playing the dragon",
            "In the base is so",
            "In the base is near",
            "Playing the mountain king",
            "In the beast is king",
            "In the beast is on",
            "The halls of the heat",
            "Flying the heat is king",
            "Playing the heat is on",
            "Singing to you all night",
            "The halls of the beast",
            "Feel the heat is on",
            "The heat is near",
            "Feel the beast is near",
            "The base is near",
            "Playing the base is king",
            "The halls of the walls",
            "The halls of the guitars",
            "Playing the base is near",
            "Flying the heat is on"
        };
    }
}
